# Generated by Django 3.0.7 on 2020-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('profesion', models.CharField(max_length=20)),
                ('universidad', models.CharField(max_length=25)),
                ('puesto', models.CharField(max_length=20)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
