# Generated by Django 3.0.7 on 2020-06-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=25)),
                ('seccion', models.CharField(max_length=25)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
